[build]
  command = "hugo --gc -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.124.1"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
