backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
local_backend: true # npx decap-server
collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    # path: '{{slug}}/index'
    filter: {field: "cms_exclude"}
    create: true
    # slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string', required: false }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', picker_utc: false, format: "YYYY-MM-DDTHH:mm:ss+08:00" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      # - { label: "Show Summary", name: "show_summary", widget: "boolean", default: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    folder: 'content/'
    create: true
    # slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', picker_utc: false, format: "YYYY-MM-DDTHH:mm:ss+08:00" }
      - { label: "Toc", name: "toc", widget: "boolean", default: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
